### ISSUE TITLE
.nodeify is not a function error

### ISSUE THREAD

**Issue by sbeatz** [shimohq/ioredis-tree#8]
MacBook-Pro:JS henrik$ node index.js
/Users/henrik/Documents/Docker/JS/node_modules/ioredis-tree/index.js:62
      return tinsert.apply(redis, argv).nodeify(callback);
                                        ^

TypeError: tinsert.apply(...).nodeify is not a function
    at RedisTree.redis.tinsert (/Users/henrik/Documents/Docker/JS/node_modules/ioredis-tree/index.js:62:41)
    at Object.<anonymous> (/Users/henrik/Documents/Docker/JS/index.js:4:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
MacBook-Pro:JS henrik$

tried to simply follow the docs but it just gives the error above
is there something missing?

**Comment by luin** [comment]
ioredis-tree only works with ioredis v3.x currently since ioredis v4.x has removed bluebird in favor of native Promise.

I’ll make a fix soon.

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by luin** [comment]
Fixed in v1.0.1.
